[package]
name = "pocket-drive"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1", features = ["full"] }
notify = "8.1.0"
notify-debouncer-full = "0.5.0"
file-hashing = "0.1.2"
blake2 = "0.10.6"
sqlite = "0.37.0"
